# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
# disqus: dbyll
# google_analytics: dbyll
title: HaeJune
repository: "haejunejung/haejunejung.github.io"

comments: 
  provider: "utterances"
  utterances:
    theme: "photon-dark"
    issue_term: "pathname"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Welcome to Haejune's Blog!
    comments: true


author:
  name: haejunejung
  email: jhj9422@unist.ac.kr
  github: haejunejung
  # twitter: dbtek
  # pinterest: asd123
  # linkedin: asd123
  bio: Record everything
  # email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
