name: Merge configure branch

on:
  schedule:
    - cron: "55 * * * *"

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        submodules: 'recursive'
    - name: Checkout configure branch
      uses: actions/checkout@v2
      with:
        ref: configure
        submodules: 'recursive'
    - name: Deploy Github Pages
      run: |
        git branch -D gh-pages || true
        git checkout --orphan gh-pages
        bundle install
        bundle exec jekyll build
        cp -r _site/* .
        git add .
        git commit -m "Build and deploy site"
        git push origin gh-pages
    - name: Merge configure branch
      if: success()
      run: |
        git checkout main
        git merge configure
        git push origin main
